// <auto-generated />
using ContaCadastroAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContaCadastroAPI.Migrations
{
    [DbContext(typeof(ContaContext))]
    [Migration("20220329163413_CriarTabelasComRelacionamentos")]
    partial class CriarTabelasComRelacionamentos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("ContaCadastroAPI.Models.ContaCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("text");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ContasCliente");
                });

            modelBuilder.Entity("ContaCadastroAPI.Models.ContaParceiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ContaClienteId")
                        .HasColumnType("int");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("text");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContaClienteId");

                    b.ToTable("ContasParceiro");
                });

            modelBuilder.Entity("ContaCadastroAPI.Models.ContaParceiro", b =>
                {
                    b.HasOne("ContaCadastroAPI.Models.ContaCliente", "ContaCliente")
                        .WithMany("ContasParceiro")
                        .HasForeignKey("ContaClienteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ContaCliente");
                });

            modelBuilder.Entity("ContaCadastroAPI.Models.ContaCliente", b =>
                {
                    b.Navigation("ContasParceiro");
                });
#pragma warning restore 612, 618
        }
    }
}
